// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"time"
)

type Log struct {
	ID       int64
	Content  string
	Category string
	DoneAt   time.Time
}
