// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Log struct {
	ID        uuid.UUID
	Content   string
	Category  string
	DoneAt    time.Time
	CreatedAt time.Time
}
