// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"database/sql"
	"time"
)

type Log struct {
	ID        int64
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
